const specs = {
  recipe_list: '../test/recipe_list/recipe_list.spec.js',

  // verifyRecipeList: '../test/postpaidCreditBalanceFlow/postpaidCreditBalanceFlow.spec.js',
  // productAocNavigation: '../test/productAocNavigation/productAocNavigation.spec.js',
  // plansAndLmsPackPurchase: '../test/plansAndLmsPackPurchase/plansAndLmsPackPurchase.spec.js',
  // amarOfferBundlePackPurchase: '../test/amarOfferBundlePackPurchase/amarOfferBundlePackPurchase.spec.js',
  // amarOfferMinutePackPurchase: '../test/amarOfferMinutePackPurchase/amarOfferMinutePackPurchase.spec.js',
  // amarOfferSmsPackPurchase: '../test/amarOfferSmsPackPurchase/amarOfferSmsPackPurchase.spec.js',
  // amarOfferInternetPackPurchase: '../test/amarOfferInternetPackPurchase/amarOfferInternetPackPurchase.spec.js',
  // amarOfferPurchaseFlow: '../test/amarOfferPurchaseFlow/amarOfferPurchaseFlow.spec.js',
  // rechargePageFlow: '../test/rechargePageFlow/rechargePageFlow.spec.js',
  // referAndEarnFlow: '../test/referAndEarnFlow/referAndEarnFlow.spec.js',
  // balanceInfo: '../test/balanceInfo/balanceInfo.spec.js',
  // productAocPurchaseFlow: '../test/productAocPurchaseFlow/productAocPurchaseFlow.spec.js',
  // cashbackRechargePaymentOption: '../test/cashbackRechargePaymentOption/cashbackRechargePaymentOption.spec.js',
  // myPlanNavigation: '../test/myPlanNavigation/myPlanNavigation.spec.js',
  // vasFlow: '../test/vasFlow/vasFlow.spec.js',
  // loanFunctionalityFlow: '../test/loanFunctionalityFlow/loanFunctionalityFlow.spec.js',
  // packPurchase: '../test/packPurchase/packPurchase.spec.js',
  // bkashPaymentOptionsOnRechargePage: '../test/bkashPaymentOptionsOnRechargePage/bkashPaymentOptionsOnRechargePage.spec.js',
  // buyNowPayLater: '../test/buyNowPayLater/buyNowPayLater.spec.js',
  // bkashUnbindedFlow: '../test/bkashUnbindedFlow/bkashUnbindedFlow.spec.js',
  // bkashBindedFlow: '../test/bkashBindedFlow/bkashBindedFlow.spec.js',
  // toffeeContentFlow: '../test/toffeeContentFlow/toffeeContentFlow.spec.js',
  // plansAndOfferCheck: '../test/plansAndOfferCheck/plansAndOfferCheck.spec.js',
  // simListFlow: '../test/simListFlow/simListFlow.spec.js',
  // menuOptionsFlow: '../test/menuOptionsFlow/menuOptionsFlow.spec.js',
  // nboProductFlow: '../test/nboProductFlow/nboProductFlow.spec.js',
  // usageHistory: '../test/usageHistory/usageHistory.spec.js',
  // blLogoutFlow: '../test/blLogoutFlow/blLogoutFlow.spec.js',
  // simBlock: '../test/simBlock/simBlock.spec.js',
  // islamicSectionFeaturesCheck: '../test/islamicSectionFeaturesCheck/islamicSectionFeaturesCheck.spec.js',
  // courses: '../test/courses/courses.spec.js',
  // guestUser: '../test/guestUser/guestUser.spec.js',
  // homepageNavbar: '../test/homepageNavbar/homepageNavbar.spec.js',
  // changePasswordFlow: '../test/changePasswordFlow/changePasswordFlow.spec.js',
  // bondhoSimPackPurchase: '../test/bondhoSimPackPurchase/bondhoSimPackPurchase.spec.js',
  // iScreen: '../test/iScreen/iScreen.spec.js',
  // audiobook: '../test/audioBook/audioBook.spec.js',
  // postpaidInsufficientLimit: '../test/postpaidInsufficientLimit/postpaidInsufficientLimit.spec.js',
  // bestDealsOffer: '../test/bestDealsOffer/bestDealsOffer.spec.js',
  // balanceTransferFlow: '../test/balanceTransferFlow/balanceTransferFlow.spec.js',
  // newSimOffer: '../test/newSimOffer/newSimOffer.spec.js',
  // missedCallAlert: '../test/missedCallAlert/missedCallAlert.spec.js',
  // careDoctorCall: '../test/careDoctorCall/careDoctorCall.spec.js',
  // commerceFilterChips: '../test/commerceFilterChips/commerceFilterChips.spec.js',
  // commerceTicketsBus: '../test/commerceTicketsBus/commerceTicketsBus.spec.js',
  // commerceUtilityElectricity: '../test/commerceUtilityElectricity/commerceUtilityElectricity.spec.js',
  // commerceUtilityGas: '../test/commerceUtilityGas/commerceUtilityGas.spec.js',
  // commerceUtilityWasa: '../test/commerceUtilityWasa/commerceUtilityWasa.spec.js',
  // nonBlUser: '../test/nonBlUser/nonBlUser.spec.js',
  // lodgeComplaint: '../test/lodgeComplaint/lodgeComplaint.spec.js',
  // switchAccountNavigation: '../test/switchAccountNavigation/switchAccountNavigation.spec.js',
  // tasbeehSectionFeatures: '../test/tasbeehSectionFeatures/tasbeehSectionFeatures.spec.js',
  // nonBlLoginWithOtp: '../test/nonBlLoginWithOtp/nonBlLoginWithOtp.spec.js',
  // lmsCoinHistory: '../test/lmsCoinHistory/lmsCoinHistory.spec.js',
  // lmsPartnerOffer: '../test/lmsPartnerOffer/lmsPartnerOffer.spec.js',
  // lmsUseCoins: '../test/lmsUseCoins/lmsUseCoins.spec.js',
  // lmsEarnCoins: '../test/lmsEarnCoins/lmsEarnCoins.spec.js',
  // lmsShortcutOffer: '../test/lmsShortcutOffer/lmsShortcutOffer.spec.js',
  // lmsPartnerDiscount: '../test/lmsPartnerDiscount/lmsPartnerDiscount.spec.js',
  // blLoginWithPassword: '../test/blLoginWithPassword/blLoginWithPassword.spec.js',
  // logout: '../test/logout/logout.spec.js'
}

const suites = {
  all: [Object.values(specs)],
  recipe_list: [
    specs.recipe_list,
  ],
};

module.exports = {
  specs,
  suites
};

